---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-snapshot-controller
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/snapshot-controller/app
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: lab-repository
  commonMetadata:
    labels:
      app.kubernetes.io/name: snapshot-controller
  prune: true
  wait: true
  interval: 10m