---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - database
    tolerations:
      - key: "role"
        operator: "Equal"
        value: "database"
        effect: "NoSchedule"
  storage:
    size: 15Gi
    storageClass: local-path
  bootstrap:
    initdb:
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
  postgresql:
    shared_preload_libraries: ["vectors.so"]
    parameters:
      max_connections: "300"
      work_mem: 64MB
      shared_buffers: 128MB
  superuserSecret:
    name: database-secret
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      memory: 2Gi