---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name database-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: database-secret-store
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: SUPERUSER_USERNAME
    - secretKey: password
      remoteRef:
        key: SUPERUSER_PASSWORD