---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lobe-chat
  namespace: flux-system
spec:
  replicaCount: 1
  timeout: 5m
  chart:
    spec:
      chart: lobe-chat
      version: 0.1.46
      sourceRef:
        kind: HelmRepository
        name: darox
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: lobehub/lobe-chat
      pullPolicy: Always
      tag: "v0.154.5"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        ingress.cilium.io/loadbalancer-mode: shared
      hosts:
        - host: chat.space.nade.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: chat-ui-tls
          hosts:
            - chat.space.nade.me
    env:
      - name: NEXT_AUTH_SSO_PROVIDERS
        value: "authentik"
      - name: AUTH_AUTHELIA_ISSUER
        value: "https://auth.nade.me"
      - name: AUTH_AUTHELIA_ID
        value: "lobe-chat"
      - name: NEXT_PUBLIC_SERVICE_MODE
        value: "server"

    envFromSecret: lobe-chat-secret
