---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lobe-chat
  namespace: flux-system
spec:
  timeout: 5m
  chart:
    spec:
      chart: lobe-chat
      version: 0.1.46
      sourceRef:
        kind: HelmRepository
        name: darox
        namespace: flux-system
  interval: 30m
  values:
    replicaCount: 1
    image:
      repository: lobehub/lobe-chat-database
      pullPolicy: Always
      tag: "v1.26.11"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        ingress.cilium.io/loadbalancer-mode: shared
      hosts:
        - host: chat.space.nade.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: chat-ui-tls
          hosts:
            - chat.space.nade.me
    env:
      - name: ENABLED_OPENAI
        value: "0"
      - name: ENABLED_OLLAMA
        value: "0"
      - name: NEXT_PUBLIC_ENABLE_NEXT_AUTH
        value: "true"
      - name: NEXT_AUTH_SSO_PROVIDERS
        value: "authelia"
      - name: AUTH_AUTHELIA_ISSUER
        value: "https://auth.nade.me"
      - name: APP_URL
        value: "https://chat.space.nade.me"
      - name: AUTH_URL
        value: "https://chat.space.nade.me/api/auth"
      - name: NEXTAUTH_URL
        value: "https://chat.space.nade.me/api/auth"
      - name: AUTH_AUTHELIA_ID
        value: "lobe-chat"
      - name: NEXT_PUBLIC_SERVICE_MODE
        value: "server"
      - name: DATABASE_URL
        value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgres-rw.database.svc.cluster.local:5432/$(DATABASE_NAME)"

    envFromSecret: lobe-chat-secret

    volumes:
      - name: app-cache
        emptyDir: {}

    volumeMounts:
      - name: app-cache
        mountPath: "/app/.next/cache"
