apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: lobe-chat-secret-store
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infisical-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infisical-secret
      secretsScope:
        projectSlug: lab-b0r6
        environmentSlug: lab
        secretsPath: /lobe-chat # Root is "/"
      hostAPI: https://app.infisical.com