---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: &name oidc-applications-secret
spec:
  namespaceSelector:
    matchLabels:
      need-oidc-secrets: "true"

  externalSecretName: *name
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: oidc-applications-secret-store
    target:
      name: *name
      creationPolicy: Owner
      template:
        engineVersion: v2
        metadata:
          labels:
            cnpg.io/reload: "true"
    dataFrom:
      - find:
          name:
            regexp: .*