apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system-metallb
  namespace: flux-system
spec:
  path: ./kubernetes/apps/metallb-system/app
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: metallb
  prune: false
  wait: true
  interval: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system-metallb-pool
  namespace: flux-system
spec:
  path: ./kubernetes/apps/metallb-system/pool
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: metallb-pool
  prune: true
  wait: false
  interval: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system-metallb-advertisement
  namespace: flux-system
spec:
  path: ./kubernetes/apps/metallb-system/advertisement
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: metallb-advertisement
  prune: true
  wait: false
  interval: 10m