apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-secrets-operator
spec:
  chart:
    spec:
      chart: secrets-operator
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: infisical-helm-charts
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 30m