---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: flux-system
spec:
  timeout: 1h
  chart:
    spec:
      chart: authelia
      version: 0.9.9
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  interval: 30m
  values:
    pod:
      extraVolumeMounts:
        - mountPath: "/external/secrets"
          name: jwk
          readOnly: true
        - mountPath: "/external/oidc-secrets"
          name: oidc-secrets
          readOnly: true
      extraVolumes:
        - name: jwk
          secret:
            secretName: authelia-secret
            items:
              - key: OIDC_CERT_CERTIFICATE
                path: "oidc.jwk.RS256.crt"
              - key: OIDC_CERT_PRIVATE_KEY
                path: "oidc.jwk.RS256.pem"
        - name: oidc-secrets
          secret:
            secretName: oidc-applications-secret
            items:
              - key: GPT_NEXT_CLIENT_SECRET
                path: "gpt-next.txt"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        ingress.cilium.io/loadbalancer-mode: shared
      tls:
        enabled: true
        secret: authelia-ui-tls
        hostNameOverride: "auth.nade.me"
      rulesOverride:
        - host: "auth.nade.me"
          path: /
    configMap:
      identity_providers:
        oidc:
          enabled: true
          jwks:
            - key_id: "default"
              use: "sig"
              algorithm: "RS256"
              key:
                path: "/external/secrets/oidc.jwk.RS256.pem"
              certificate_chain:
                path: "/external/secrets/oidc.jwk.RS256.crt"
          clients:
            # Not used in any way but Authelia helm chart requires one or more clients, plain text will do fine job ugh
            - client_id: "default"
              authorization_policy: "one_factor"
              client_name: "Default Application"
              client_secret:
                value: "$pbkdf2-sha512$310000$eDtB3EO5skFQItYupBfpIg$fTju9Y9G/5LGpNBnjepcVvvxh6s2.rFqKIGtj0vtHr5Rzf.JcZeQOjvfXuYxKGEHH22YZqp.LPDAXqMDwoB9Ow"
            - client_id: "lobe-chat"
              client_name: "LobeChat"
              authorization_policy: "one_factor"
              client_secret:
                value: "$argon2id$v=19$m=65536,t=3,p=4$p5pg3D1a7hF8MGz9hSMBaQ$JaTcO2wre4fDLKY12qyyUyyEaCs9oAmSWFzOkLbDqQ0"
              public: false
              redirect_uris:
                - https://chat.space.nade.me/api/auth/callback/authelia
              scopes:
                - openid
                - profile
                - email
              userinfo_signing_algorithm: none
      access_control:
        default_policy: "one_factor"
      authentication_backend:
        password_reset:
          disable: false
        ldap:
          implementation: custom
          enabled: true
          base_dn: "dc=example,dc=com"
          additional_users_dn: "ou=people"
          users_filter: "(&({username_attribute}={input})(objectClass=person))"
          additional_groups_dn: "ou=groups"
          groups_filter: "(member={dn})"
          attributes:
            display_name: displayName
            username: uid
            group_name: cn
            mail: mail
      rbac:
        enabled: true
      session:
        cookies:
          - subdomain: auth
            domain: "nade.me"
      storage:
        postgres:
          enabled: true
          address: "tcp://postgres-rw.database.svc.cluster.local:5432"
        redis:
          enabled: true
          host: "dragonfly.database.svc.cluster.local"
          port: 6379
      notifier:
        filesystem:
          enabled: true
  valuesFrom:
    - kind: Secret
      name: authelia-secret
      valuesKey: LDAP_BACKEND_URL
      targetPath: "configMap.authentication_backend.ldap.address"
    - kind: Secret
      name: authelia-secret
      valuesKey: DATABASE_NAME
      targetPath: "configMap.storage.postgres.database"
    - kind: Secret
      name: authelia-secret
      valuesKey: DATABASE_USER
      targetPath: "configMap.storage.postgres.username"
    - kind: Secret
      name: authelia-secret
      valuesKey: DATABASE_PASSWORD
      targetPath: "configMap.storage.postgres.password.value"
    - kind: Secret
      name: authelia-secret
      valuesKey: LDAP_BIND_USER
      targetPath: "configMap.authentication_backend.ldap.user"
    - kind: Secret
      name: authelia-secret
      valuesKey: LDAP_BIND_PASSWORD
      targetPath: "configMap.authentication_backend.ldap.password.value"
