apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values