k8sServiceHost: "5.161.199.0"
k8sServicePort: 6443

kubeProxyReplacement: true

ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: '10.244.0.0/16'

ipv4NativeRoutingCIDR: '10.244.0.0/16'

ingressController:
  enabled: true
  loadBalancerMode: shared
  default: true

loadBalancer:
  algorithm: maglev

bandwidthManager:
  enabled: true

bpf:
  masquerade: true
  tproxy: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

hostLegacyRouting: true

hostFirewall:
  enabled: true

endpointRoutes:
  enabled: true