kubeProxyReplacement: true
k8sServiceHost: "5.161.199.0"
k8sServicePort: 6443
rollOutCiliumPods: true
localRedirectPolicy: true

routingMode: native
loadBalancer:
  mode: dsr
  dsrDispatch: opt
  algorithm: maglev
hubble:
  enabled: true
  serviceMonitor:
    enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - udp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: false
agent:
  sleepAfterInit: true
