---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-external-dns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/network/external-dns/app
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname external-dns
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: security-secret-store