---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-dragonfly
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/dragonfly/operator
  targetNamespace: database
  sourceRef:
    kind: GitRepository
    name: lab-repository
  prune: true
  wait: true
  interval: 10m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-dragonfly-cluster
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/dragonfly/cluster
  targetNamespace: database
  prune: true
  sourceRef:
    kind: GitRepository
    name: lab-repository
  wait: true
  interval: 10m
  dependsOn:
    - name: database-dragonfly
    - name: storage-democratic-local-path