apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-cloudnative-pg-cluster
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/cloudnative-pg/cluster
  targetNamespace: database
  prune: true
  sourceRef:
    kind: GitRepository
    name: lab-repository
  wait: true
  interval: 10m
  dependsOn:
    - name: cnpg-system-cloudnative-pg
    - name: storage-democratic-csi-local-path
    - name: database-secret-store