apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: v0.21.6
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 30m