apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: flux-webhook-external-secret-insifical
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    # Universal Auth
    universalAuth:
      secretsScope:
        projectSlug: lab-b0r6
        envSlug: lab
        secretsPath: "/github" # Root is "/"
        recursive: false
      credentialsRef:
        secretName: infisical-secret
        secretNamespace: security
  managedSecretReference:
    secretName: flux-webhook-secret-infisical-managed
    secretNamespace: flux-system
    creationPolicy: Owner