apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/sealed-secrets/app
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: sealed-secrets-controller
  prune: false
  wait: true
  interval: 10m