---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-democratic-csi-local-path
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/democratic-csi/local-path
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: nadelab
  prune: true
  wait: true
  dependsOn:
    - name: storage-snapshot-controller
  interval: 10m