---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dragonfly-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: dragonfly-operator
      version: v1.1.6
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  values:
    rbacProxy:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v0.13.1
    serviceAccount:
      create: true
      name: *app