apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-webhook
  namespace: flux-system
spec:
  path: ./kubernetes/apps/flux-system/webhook/app
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux-webhook
  prune: false
  wait: true
  interval: 10m