apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infisical-external-secrets
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/infisical/app
  targetNamespace: security
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: infisical
  prune: false
  wait: true
  interval: 10m