apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-cloudflare
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infisical-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infisical-secret
      secretsScope:
        projectSlug: lab
        environmentSlug: lab
        secretsPath: /cloudflare
      hostAPI: https://app.infisical.com