apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cert-manager-cf-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloudflare
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: TOKEN