apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cert-manager-cf-secret-infisical
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    # Universal Auth
    universalAuth:
      secretsScope:
        projectSlug: lab-b0r6
        envSlug: lab
        secretsPath: "/cloudflare" # Root is "/"
        recursive: false
      credentialsRef:
        secretName: infisical-secret
        secretNamespace: security
  managedSecretReference:
    secretName: cert-manager-cf-secret-infisical-managed
    secretNamespace: network
    creationPolicy: Owner