apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lobe-chat
  namespace: flux-system
spec:
  path: ./kubernetes/apps/self-hosted/lobe-chat/app
  targetNamespace: self-hosted
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: lobe-chat
  prune: false
  wait: true
  interval: 10m
  dependsOn:
    - name: database-cloudnative-pg-cluster
    - name: security-external-secrets