---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: flux-system
spec:
  chart:
    spec:
      chart: lldap
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: djjudas21
        namespace: flux-system
  interval: 30m
  values:
    externalPostgresql:
      enabled: true
      auth:
        host: "postgres-rw.database.svc.cluster.local"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        ingress.cilium.io/loadbalancer-mode: shared
      hosts:
        - host: lldap.space.nade.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: lldap-ui-tls
          hosts:
            - lldap.space.nade.me
  valuesFrom:
    - kind: Secret
      name: lldap-secret
      valuesKey: DATABASE_NAME
      targetPath: "externalPostgresql.auth.database"
    - kind: Secret
      name: lldap-secret
      valuesKey: DATABASE_USER
      targetPath: "externalPostgresql.auth.username"
    - kind: Secret
      name: lldap-secret
      valuesKey: DATABASE_PASSWORD
      targetPath: "externalPostgresql.auth.password"
    - kind: Secret
      name: lldap-secret
      valuesKey: LDAP_ADMIN_PASSWORD
      targetPath: "lldap.ldapUserPass"
    - kind: Secret
      name: lldap-secret
      valuesKey: LDAP_JWT_SECRET
      targetPath: "lldap.jwtSecret"
    - kind: Secret
      name: lldap-secret
      valuesKey: LDAP_KEY_SEED
      targetPath: "lldap.keySeed"