apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  timeout: 1h
  chart:
    spec:
      chart: external-secrets
      version: 0.10.5
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 30m
  values:
    installCRDs: true
    replicaCount: 1
    leaderElect: true
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      replicaCount: 1
      serviceMonitor:
        enabled: true
        interval: 1m
      resources:
        requests:
          cpu: 15m
          memory: 50Mi
        limits:
          memory: 100Mi
    certController:
      serviceMonitor:
        enabled: true
        interval: 1m
      resources:
        requests:
          cpu: 15m
          memory: 80Mi
        limits:
          memory: 150Mi
    resources:
      requests:
        cpu: 15m
        memory: 50Mi
      limits:
        memory: 150Mi