apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/authelia/app
  targetNamespace: security
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: authelia
  prune: false
  wait: true
  interval: 10m
  dependsOn:
    - name: database-cloudnative-pg-cluster
    - name: security-external-secrets