apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: metallb
      version: v0.14.5
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system